language: ruby

rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.2
  - 2.3.5
  - 2.4.0
  - ruby-head

gemfile:
  - gemfiles/3.2.gemfile
  - gemfiles/4.2.gemfile

matrix:
  allow_failures:
    - rvm: ruby-head

env:
  - DB=sqlite

script:
  - cd spec/dummy/
  - RAILS_ENV=test bundle exec rake db:migrate
  - cd ../../
  - bundle exec rspec spec/
